FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-pytest g++ make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
