"""Simulated LLM-style report generator.

This module does not call a real LLM. It accepts the same style of structured
context that a real LLM wrapper could receive and returns a natural-language
report. This lets students test the architecture without paid API access.
"""

from __future__ import annotations


def generate_report(context: dict) -> str:
    avg = float(context["historical_average_temperature_c"])
    current = float(context["current_singapore_temperature_c"])
    location = context.get("location", "Singapore")
    condition = context.get("condition", "Unknown")

    if avg >= 28.0 and current >= 30.0:
        advice = "The indoor history and current outdoor weather both suggest warm conditions. Turning on the aircon is reasonable."
    elif avg >= 28.0:
        advice = "The indoor readings are already warm. Turn on the aircon if people are staying in the room."
    elif current >= 30.0:
        advice = "The current outdoor temperature is high, so the room may warm up soon. Aircon is reasonable if comfort is important."
    else:
        advice = "Aircon may not be necessary now. A fan or natural ventilation may be sufficient."

    return (
        "Simulated LLM Temperature Report\n\n"
        f"The historical average indoor temperature is {avg:.1f} C. "
        f"The current temperature in {location} is {current:.1f} C with condition: {condition}.\n\n"
        f"Advice: {advice}\n\n"
        "Note: this report was generated by a simulated LLM-compatible function, not a paid LLM API."
    )
